apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-controller
spec:
  ingressClassName: nginx
  rules:
    - host: localktzdev.com
      http:
       paths:
        - path: "/auth-services/"
          pathType: Prefix
          backend:
            service:
              name: "ktz-auth-service"
              port: 
                number: 7000
        - path: "/verification-services"
          pathType: Prefix
          backend:
            service: 
              name: "ktz-verification-app-srv"
              port: 
                number: 7001
        - path: "/car-services"
          pathType: Prefix
          backend:
            service:
              name: "ktz-carservice-app-srv"
              port: 
                number: 7002
        - path: "/bid-services"
          pathType: Prefix
          backend:
            service:
              name: "ktz-bidding-app-srv"
              port: 
                number: 7003
        - path: "/notification-services"
          pathType: Prefix
          backend: 
            service:
              name: "ktz-notifification-app-srv"
              port: 
                number: 7004     