apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      # - ./infra/k8s/rabbit_infra/*
      - ./infra/k8s/auth_service_k8s_infra/*
      - ./infra/k8s/bidding_service_k8s_infra/*
      - ./infra/k8s/car_services_k8s_infra/*
      - ./infra/k8s/notification_service_k8s_infra/*
      - ./infra/k8s/verification_service_k8s_infra/*
      - ./infra/k8s/load_balancer/*
      
build:
  local:       #Comment this out when uploading to the server remote
    push: off
  # googleCloudBuild:
  #   projectId: kartrenzmicroservic  
  artifacts:
    # - image: us.gcr.io/auth_services
    #   context: auth_services
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "**/*.js"
    #         dest: .  
    - image: bibybat/ktz_auth_services
      context: auth_services
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .  
    - image: bibybat/ktz_bidding_services
      context: bidding_services
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .          
    - image: bibybat/ktz_car_services
      context: car_services
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .     
    - image: bibybat/ktz_notification_services
      context: notification_services
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: . 
    - image: bibybat/ktz_verification_services
      context: verification_services
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .                               