apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktz-verification-app
  labels:
    app: ktz-verification-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktz-verification-app
  template:
    metadata:
      name: ktz-verification-app
      labels:
        app: ktz-verification-app
    spec:
      containers:
        - name: ktz-verification-app
          image: bibybat/ktz_verification_services
          port:
            - containerPort: 7001

---

apiVersion: v1
kind: Service
metadata:
  name: ktz-verification-app-srv
  labels:
    app: ktz-verification-app-srv
spec: 
  type: ClusterIP
  selector:
    labels:
      app: ktz-verification-app
  ports:
    - name: ktz-verification-app-srv-port
      protocol: TCP
      port: 7001
      targetPort: 7001
      