apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktz-verification-db
  labels:
    app: ktz-verification-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktz-verification-db
  template:
    metadata:
      name: ktz-verification-db
      labels:
        app: ktz-verification-db
    spec:
      volumes:
        - name: ktz-verification-db-storage
          persistentVolumeClaim:
            claimName:  verification-volume-claim
      containers:
        - name: ktz-verification-db
          image: mongo
          ports: 
            - containerPort: 27017
          volumeMounts:
            - name: ktz-verification-db-storage
              mountPath: "/data/db"

---

apiVersion: v1 
kind: Service
metadata:
  name: ktz-verification-db-srv
  labels:
    app: ktz-verification-db-srv
spec:
  type: ClusterIP
  selector:
    app: ktz-verification-db
  ports:
    - name: ktz-verification-db-port
      protocol: TCP
      port: 27017
      targetPort: 27017