apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-mq-deployment
  labels:
    app: rabbit-mq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-mq-deployment
  template:
      metadata:
        labels:
          app:  rabbit-mq-deployment
      spec:
        containers:
          - name:  rabbit-mq-deployment
            image: rabbitmq:3.8.19-management
            ports:
            - containerPort: 5672
            - containerPort: 15672   

---

apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq-service
spec:
  type: ClusterIP
  selector:
    app: rabbit-mq-deployment
  ports:
    - name: rabbit-mq-default
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: rabbit-mq-management-ui
      protocol: TCP
      port: 15672
      targetPort: 15672    