apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktz-auth-db
  labels:
    app: ktz-auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktz-auth-db
  template:
    metadata:
      name: ktz-auth-db
      labels:
        app: ktz-auth-db
    spec:
      containers:
        - name: ktz-auth-mongo-db
          image: mongo
          ports:
            - containerPort: 7000


---

apiVersion: v1
kind: Service
metadata:
  name: ktz-auth-db-srv
  labels:
    app: ktz-auth-db-srv

spec:
  selector:
    app: ktz-auth-db
  ports:
    - name: ktz-auth-db-port
      protocol: TCP
      port: 27017
      targetPort: 27017
