apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktz-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktz-auth
  template:
    metadata:
      labels:
        app: ktz-auth
    spec:  
      containers:
        - name: ktz-auth
          image: bibybat/ktz_auth_services
          ports:
            - containerPort: 7000

---

apiVersion: v1
kind: Service
metadata:
  name: ktz-auth-service
  labels:
    app: ktz-auth-service
spec:
   selector:
     app: ktz-auth
   ports:
      - name: ktz-auth
        protocol: TCP
        port: 7000
        targetPort: 7000
