apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktz-notification-db
  labels:
    app: ktz-notification-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktz-notification-db
  template:
    metadata:
      name: ktz-notification-db
      labels:
        app: ktz-notification-db
    spec:
      volumes:
        - name: ktz-notification-db-storage
          persistentVolumeClaim:
            claimName: notification-volume-claim
      containers:
        - name: ktz-notification-db
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: ktz-notification-db-storage
              mountPath: "/data/db"

---

apiVersion: v1
kind: Service
metadata:
  name: ktz-notification-db-srv
  labels:
    app: ktz-notification-db-srv
spec:
  type: ClusterIP
  selector:
    app:  ktz-notification-db
  ports:
    - name: ktz-notification-db-port
      protocol: TCP
      port: 27017
      targetPort: 27017  