apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktz-notification-db
  labels:
    app: ktz-notification-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktz-notification-db
  template:
    metadata:
      name: ktz-notification-db
      labels:
        app: ktz-notification-db
    spec:
      containers:
        - name: ktz-notification-db
          image: mongo
          port:
            - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: ktz-notification-db-srv
  labels:
    app: ktz-notification-db-srv
spec:
  kind: ClusterIP
  selector:
    app:  ktz-notification-db
  ports:
    - name: ktz-notification-db-port
      protocol: TCP
      port: 27017
      targetPort: 27017  